<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB;
use Carbon\Carbon;
use App\RentalPayment;
use Illuminate\Support\Facades\Hash;
use App\Traits\AllServices;

class RentalPaymentController extends Controller
{
    use AllServices;

    private $controllerName = '[RentalPaymentController]';

    public function index(Request $request)
    {
        error_log($this->controllerName . 'Retrieving list of rentalPayments.');
        // api/rentalPayment (GET)
        $rentalPayments = $this->getRentalPayments($request->user());
        if ($this->isEmpty($rentalPayments)) {
            return $this->errorPaginateResponse('RentalPayments');
        } else {
            return $this->successPaginateResponse('RentalPayments', $rentalPayments, $this->toInt($request->pageSize), $this->toInt($request->pageNumber));
        }
    }

    public function filter(Request $request)
    {
        error_log($this->controllerName . 'Retrieving list of filtered rentalPayments.');
        // api/rentalPayment/filter (GET)
        $params = collect([
            'keyword' => $request->keyword,
            'fromdate' => $request->fromdate,
            'todate' => $request->todate,
            'rentalPaymentTypes' => $request->rentalPaymentTypes,
            'status' => $request->status,
        ]);
        //Convert To Json Object
        $params = json_decode(json_encode($params));
        $rentalPayments = $this->getRentalPayments($request->user());
        $rentalPayments = $this->filterRentalPayments($rentalPayments, $params);

        if ($this->isEmpty($rentalPayments)) {
            return $this->errorPaginateResponse('RentalPayments');
        } else {
            return $this->successPaginateResponse('RentalPayments', $rentalPayments, $this->toInt($request->pageSize), $this->toInt($request->pageNumber));
        }
    }

    public function show(Request $request, $uid)
    {
        // api/rentalPayment/{rentalPaymentid} (GET)
        error_log($this->controllerName . 'Retrieving rentalPayment of uid:' . $uid);
        $rentalPayment = $this->getRentalPayment($uid);
        if ($this->isEmpty($rentalPayment)) {
            $data['data'] = null;
            return $this->notFoundResponse('RentalPayment');
        } else {
            return $this->successResponse('RentalPayment', $rentalPayment, 'retrieve');
        }
    }

    public function store(Request $request)
    {
        DB::beginTransaction();
        // Can only be used by Authorized personnel
        // api/rentalPayment (POST)
        $this->validate($request, [
            'room_contract_id' => 'required|numeric',
        ]);
        error_log($this->controllerName . 'Creating rentalPayment.');

        $roomContract = $this->getRoomContractById($request->room_contract_id);

        if ($this->isEmpty($roomContract)) {
            DB::rollBack();
            return $this->errorResponse();
        }

        if ($roomContract->leftmonth > 0) {

            $room = $roomContract->room;
            if ($this->isEmpty($room)) {
                DB::rollBack();
                return $this->errorResponse();
            }
            $rentalDate = $this->toDate(Carbon::parse($roomContract->startdate)->addMonth($roomContract->duration - $roomContract->leftmonth)->startOfMonth());
            $rentalPayment = new RentalPayment();
            $rentalPayment->uid = Carbon::now()->timestamp . RentalPayment::count();
            $params = collect([
                'price' => $room->price,
                'rentaldate' => $rentalDate,
                'remark' => "This rental is generated by system monthly automatically.",
                'room_contract_id' => $roomContract->id,
            ]);
            //Convert To Json Object
            $params = json_decode(json_encode($params));
            $rentalPayment = $this->createRentalPayment($params);

            if ($this->isEmpty($rentalPayment)) {
                DB::rollBack();
                return $this->errorResponse();
            }

            $roomContract->leftmonth -= 1;
            if (!$this->saveModel($roomContract)) {
                DB::rollBack();
                return $this->errorResponse();
            }
        } else {

            //Renew Contract
            if ($roomContract->autorenew) { }
        }



        DB::commit();
        return $this->successResponse('RentalPayment', $rentalPayment, 'create');
    }

    public function update(Request $request, $uid)
    {
        DB::beginTransaction();
        // api/rentalPayment/{rentalPaymentid} (PUT)
        error_log($this->controllerName . 'Updating rentalPayment of uid: ' . $uid);
        $rentalPayment = $this->getRentalPayment($uid);
        $this->validate($request, [
            'name' => 'required|string|max:300',
            'address' => 'nullable|string|max:300',
            'postcode' => 'nullable|string|max:300',
            'state' => 'nullable|string|max:300',
            'city' => 'nullable|string|max:300',
            'country' => 'nullable|string|max:300',
            'price' => 'required|numeric',
            'rentalPaymentTypes' => 'required',
        ]);
        if ($this->isEmpty($rentalPayment)) {
            DB::rollBack();
            return $this->notFoundResponse('RentalPayment');
        }
        $params = collect([
            'name' => $request->name,
            'address' => $request->address,
            'postcode' => $request->postcode,
            'state' => $request->state,
            'city' => $request->city,
            'country' => $request->country,
            'price' => $request->price,
        ]);
        //Convert To Json Object
        $params = json_decode(json_encode($params));
        $rentalPayment = $this->updateRentalPayment($rentalPayment, $params);

        if ($this->isEmpty($rentalPayment)) {
            DB::rollBack();
            return $this->errorResponse();
        }

        $rentalPaymentTypes = RentalPaymentType::find($request->rentalPaymentTypes);
        if ($this->isEmpty($rentalPaymentTypes)) {
            DB::rollBack();
            return $this->notFoundResponse('RentalPaymentType');
        }

        try {
            $rentalPayment->rentalPaymentTypes()->sync($rentalPaymentTypes->pluck('id'));
        } catch (Exception $e) {
            DB::rollBack();
            return $this->errorResponse();
        }
        DB::commit();
        return $this->successResponse('RentalPayment', $rentalPayment, 'update');
    }

    public function destroy(Request $request, $uid)
    {
        DB::beginTransaction();
        // TODO ONLY TOGGLES THE status = 1/0
        // api/rentalPayment/{rentalPaymentid} (DELETE)
        error_log($this->controllerName . 'Deleting rentalPayment of uid: ' . $uid);
        $rentalPayment = $this->getRentalPayment($uid);
        if ($this->isEmpty($rentalPayment)) {
            DB::rollBack();
            return $this->notFoundResponse('RentalPayment');
        }
        $rentalPayment = $this->deleteRentalPayment($rentalPayment);
        if ($this->isEmpty($rentalPayment)) {
            DB::rollBack();
            return $this->errorResponse();
        }


        DB::commit();
        return $this->successResponse('RentalPayment', $rentalPayment, 'delete');
    }
}
